### Sign up
POST {{host}}/api/account/signup
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Bobson",
    "email": "bob5@domain.com",
    "password": "bob"
}

### Sign in
POST {{host}}/api/account/signin
Content-Type: application/json

{
    "email": "bob5@domain.com",
    "password": "bob"
}

### Get account details
POST {{host}}/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDI2ZDk4ZmUtYTlhZi00YjFiLWE1YTktZjU5NGVhMTQ4MmZhIiwibmJmIjoxNjk5OTUzOTQ2LCJleHAiOjE2OTk5OTcxNDYsImlhdCI6MTY5OTk1Mzk0NiwiaXNzIjoiaHR0cHM6Ly9tYW5lcm8uY29tIiwiYXVkIjoiaHR0cHM6Ly9tYW5lcm8uY29tIn0.P1OHbkef_3k6cvCZGEHNQmrnOmUhRoFC7W6HO2xAG1M
