### Sign up
POST {{host}}/api/account/signup
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Bobson",
    "email": "bob5@domain.com",
    "password": "bob"
}

### Sign in
POST {{host}}/api/account/signin
Content-Type: application/json

{
    "email": "bob@domain.com",
    "password": "bob"
}

### Get account details
POST {{host}}/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjNmZjUyODMtNmY0NC00MWM4LWE5YjMtN2U1MmMyZDQxMmYwIiwibmJmIjoxNjk5OTY3MDc5LCJleHAiOjE3MDAwMTAyNzksImlhdCI6MTY5OTk2NzA3OSwiaXNzIjoiaHR0cHM6Ly9tYW5lcm8uY29tIiwiYXVkIjoiaHR0cHM6Ly9tYW5lcm8uY29tIn0.w1IahqEi7WKUDiFvqBaNfCJlV06vewwQIQyaWzEjBp0
