### Get all orders
GET {{host}}/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJmM2ZmNTI4My02ZjQ0LTQxYzgtYTliMy03ZTUyYzJkNDEyZjAiLCJuYmYiOjE2OTk4ODcyNTcsImV4cCI6MTcyMDg4MjQ1NywiaWF0IjoxNjk5ODg3MjU3LCJpc3MiOiJodHRwczovL21hbmVyby5jb20iLCJhdWQiOiJodHRwczovL21hbmVyby5jb20ifQ.lFVXFMvOkARrEg9nt-pQMtZTBd8Pcv-JAfUQiJVqNaM

### Post order
POST {{host}}/api/orders
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Bäckström",
    "email": "simon@mail.com",
    "phoneNumber": "123 456 78 90",
    "streetAddress": "Gata 100",
    "city": "Staden",
    "postalCode": "12345",
    "items": [
        {
            "productId": 1,
            "sizeId": 1,
            "quantity": 1
        },
        {
            "productId": 2,
            "sizeId": 2,
            "quantity": 2
        }
    ]
}
