### Get all orders
GET {{host}}/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjNmZjUyODMtNmY0NC00MWM4LWE5YjMtN2U1MmMyZDQxMmYwIiwibmJmIjoxNjk5OTY3MDc5LCJleHAiOjE3MDAwMTAyNzksImlhdCI6MTY5OTk2NzA3OSwiaXNzIjoiaHR0cHM6Ly9tYW5lcm8uY29tIiwiYXVkIjoiaHR0cHM6Ly9tYW5lcm8uY29tIn0.w1IahqEi7WKUDiFvqBaNfCJlV06vewwQIQyaWzEjBp0

### Post order
POST {{host}}/api/orders
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjNmZjUyODMtNmY0NC00MWM4LWE5YjMtN2U1MmMyZDQxMmYwIiwibmJmIjoxNjk5OTY3MDc5LCJleHAiOjE3MDAwMTAyNzksImlhdCI6MTY5OTk2NzA3OSwiaXNzIjoiaHR0cHM6Ly9tYW5lcm8uY29tIiwiYXVkIjoiaHR0cHM6Ly9tYW5lcm8uY29tIn0.w1IahqEi7WKUDiFvqBaNfCJlV06vewwQIQyaWzEjBp0

{
    "firstName": "Bob",
    "lastName": "Bobson",
    "email": "bob@domain.com",
    "phoneNumber": "1234567890",
    "streetAddress": "Gata 100",
    "city": "Staden",
    "postalCode": "12345",
    "items": [
        {
            "productId": 1,
            "sizeId": 1,
            "quantity": 1
        },
        {
            "productId": 2,
            "sizeId": 2,
            "quantity": 2
        }
    ]
}
